# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0040_alter_exercise_license_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='intent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Intent'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_pattern',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Movement Pattern'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='historicalexercise',
            name='intent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Intent'),
        ),
        migrations.AddField(
            model_name='historicalexercise',
            name='movement_pattern',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Movement Pattern'),
        ),
        migrations.AddField(
            model_name='historicalexercise',
            name='video_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Video URL'),
        ),
    ]
