# Generated by Django 6.0.8 on 2026-09-07 16:33

import django.db.models.deletion
import wger.utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile_timezone'),
        ('nutrition', '0037_powersync_synced_ingredient_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_title', models.CharField(blank=True, max_length=300, verbose_name='The original title of this object, if available')),
                ('license_object_url', models.URLField(blank=True, verbose_name='Link to original object, if available')),
                ('license_author', models.TextField(blank=True, default='', help_text='If you are not the author, enter the name or source here.', max_length=3500, verbose_name='Author(s)')),
                ('license_author_url', models.URLField(blank=True, verbose_name='Link to author profile, if available')),
                ('license_derivative_source_url', models.URLField(blank=True, help_text='Note that a derivative work is one which is not only based on a previous work, but which also contains sufficient new, creative content to entitle it to its own copyright.', verbose_name='Link to the original source, if this is a derivative work')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('license', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.license', verbose_name='License')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
            bases=(wger.utils.models.AbstractHistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='nutrition.recipe')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.ingredientweightunit')),
            ],
        ),
    ]
